import { bitebyte_logo, kateeva, coding_temple, offtheweights_logo } from "../assets/images";
import {
    offtheweights,
    contact,
    css,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    nextjs,
    nodejs,
    bitebyte,
    react,
    avatar,
    pokemon,
    handstand,
    tailwindcss,
    typescript,
    trainersmemory,
    python,
    flask,
    postgresql,
    firebase,
    tensorflow,
    threejs,
    googlecloud,
    healthbridge,
    healthchat,
} from "../assets/icons";

export const skills = [
    { imageUrl: python, name: "Python", type: "Backend" },
    { imageUrl: javascript, name: "JavaScript", type: "Frontend" },
    { imageUrl: typescript, name: "TypeScript", type: "Frontend" },
    { imageUrl: react, name: "React", type: "Frontend" },
    { imageUrl: nextjs, name: "Next.js", type: "Frontend" },
    { imageUrl: threejs, name: "Three.js", type: "3D" },
    { imageUrl: tailwindcss, name: "Tailwind CSS", type: "Frontend" },
    { imageUrl: html, name: "HTML", type: "Frontend" },
    { imageUrl: css, name: "CSS", type: "Frontend" },
    { imageUrl: nodejs, name: "Node.js", type: "Backend" },
    { imageUrl: express, name: "Express", type: "Backend" },
    { imageUrl: flask, name: "Flask", type: "Backend" },
    { imageUrl: postgresql, name: "PostgreSQL", type: "Database" },
    { imageUrl: firebase, name: "Firebase", type: "Database" },
    { imageUrl: googlecloud, name: "Google Cloud", type: "Cloud" },
    { imageUrl: tensorflow, name: "TensorFlow.js", type: "AI/ML" },
    { imageUrl: git, name: "Git", type: "Version Control" },
    { imageUrl: github, name: "GitHub", type: "Version Control" },
];

export const experiences = [
    {
        title: "Software Developer",
        company_name: "Co.Lab",
        icon: bitebyte_logo,
        iconBg: "#E6EFED",
        date: "March 2024 - June 2024",
        points: [
            "Spearheaded development as Lead Developer of BiteByte, an AI-powered nutrition tracking app that received highest ratings in Co.Lab bootcamp.",
            "Engineered AI image recognition with 90%+ nutritional analysis accuracy through Google Cloud Vision and Edamam APIs integration.",
            "Designed scalable backend architecture integrating multiple AI services with Firebase real-time database.",
            "Built cross-device camera functionality using MediaDevices API, enabling seamless photo uploads for AI analysis.",
        ],
    },
    {
        title: "Software Developer",
        company_name: "Coding Temple",
        icon: coding_temple,
        iconBg: "#000000",
        date: "January 2024 - March 2024",
        points: [
            "Developed full-stack web applications using Python, Flask, and React with RESTful APIs and SQL integration in a 600-hour bootcamp.",
            "Architected responsive web interfaces with React components and state management for dynamic single-page applications.",
            "Applied OOP principles to build scalable Python applications with advanced data structures and algorithms.",
            "Utilized Git for version control and collaborative development across multiple team projects.",
        ],
    },
    {
        title: "Fitness Coach",
        company_name: "Multiple Premium Fitness Facilities",
        icon: offtheweights_logo,
        iconBg: "#002147",
        date: "March 2020 - Present",
        points: [
            "Trained athletes from youth to professional levels, contributing to NBA, G-League placements, and collegiate scholarships.",
            "Implemented performance tracking systems resulting in 6% average body fat loss and 25% strength increases across clients.",
            "Achieved 95% client retention rate through personalized training programs and evidence-based coaching methods.",
            "Coached 75-85 client sessions monthly with customized workout plans and nutrition guidance.",
        ],
    },
    {
        title: "Software Test Automation Engineer",
        company_name: "Kateeva",
        icon: kateeva,
        iconBg: "#fbc3bc",
        date: "August 2017 - February 2020",
        points: [
            "Developed automated testing suite for five industrial printer systems, reducing testing time from 1 week to 8 hours.",
            "Engineered comprehensive regression testing framework improving test coverage by 30% while reducing testing time by 65%.",
            "Partnered with cross-functional teams to define requirements and execute system, unit, and acceptance tests.",
            "Automated critical workflows contributing to 10+ major releases and 50+ patches, reducing production issues by 15%.",
            "Created standardized test protocols ensuring repeatable and reliable quality assurance processes.",
        ],
    },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/alexandrehuynh',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/alexvahuynh/',
    }
];

export const projects = [
    {
        iconUrl: trainersmemory,
        theme: 'btn-back-blue',
        name: 'Trainers Memory',
        description: 'An AI-powered fitness intelligence layer that lets any fitness platform understand, analyze, and derive insights from client workout data. The API gives fitness companies personalized AI coaching without building their own AI infrastructure.',
        link: 'https://trainers-memory.vercel.app/',
    },
    {
        iconUrl: handstand,
        theme: 'btn-back-orange',
        name: 'EyeSpyAI',
        description: 'Real-time exercise form analysis for squats, push-ups, and lunges. MediaPipe pose detection and TensorFlow.js deliver instant visual and audio feedback, backed by a TypeScript/Express API and PostgreSQL for workout history.',
        link: 'https://eyespyai.replit.app/',
        codeLink: 'https://github.com/alexandrehuynh/eyespyAI',
    },
    {
        iconUrl: healthbridge,
        theme: 'btn-back-purple',
        name: 'HealthBridge',
        description: 'A mobile-first, multilingual web app that helps newcomers to Canada navigate the gap before they become eligible for public healthcare.',
        link: 'https://healthbridge-ca.replit.app/',
        codeLink: 'https://github.com/alexandrehuynh/healthbridge',
    },
    {
        iconUrl: healthchat,
        theme: 'btn-back-black',
        name: 'HealthChat AI',
        description: 'A full-stack tool for testing and evaluating AI chatbot responses in healthcare contexts, with safety validation, compliance checks, and scoring across scenarios like wellness coaching, medication reminders, and health screening.',
        codeLink: 'https://github.com/alexandrehuynh/healthchatAI',
    },
    {
        iconUrl: bitebyte,
        theme: 'btn-back-green',
        name: 'BiteByte',
        description: 'A progressive web app that gives users a macronutrient breakdown of a meal from a single photo, using Google Cloud Vision and the Edamam API.',
        link: 'https://bitebyte.onrender.com/',
        codeLink: 'https://github.com/alexandrehuynh/BiteByte',
    },
    {
        iconUrl: offtheweights,
        theme: 'btn-back-yellow',
        name: 'OFFTHEWEIGHTS',
        description: 'The website for my fitness coaching brand, helping clients find programs and reach their fitness goals.',
        link: 'https://www.offtheweights.com/',
    },
    {
        iconUrl: pokemon,
        theme: 'btn-back-red',
        name: 'Pokemon Capture',
        description: 'A web app where users capture Pokemon and train them to battle other users.',
        link: 'https://pokemon-battle-abc62.web.app/',
        codeLink: 'https://github.com/alexandrehuynh/pokemon_capture',
    },
    {
        iconUrl: avatar,
        theme: 'btn-back-pink',
        name: 'Avatar RPG Character Creator',
        description: 'A TypeScript RPG character selection screen that lets users build their own character.',
        link: 'https://typescript-rpg.onrender.com/',
        codeLink: 'https://github.com/alexandrehuynh/typescript_RPG',
    },
];
